"""Add user_id

Revision ID: eee0acce8b34
Revises: 66692cb04869
Create Date: 2024-01-04 22:50:18.964769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee0acce8b34'
down_revision = '66692cb04869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
