"""Change uuid to integer

Revision ID: f42af3d26f79
Revises: de1e4837689c
Create Date: 2024-01-04 23:26:06.739175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42af3d26f79'
down_revision = 'de1e4837689c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
