"""Add Category

Revision ID: 5f5a88299277
Revises: 4feab62e1d07
Create Date: 2023-12-26 19:17:44.833631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5a88299277'
down_revision = '4feab62e1d07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('earnings', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'earnings', 'category', ['category_id'], ['id'])
    op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'category_id')
    op.drop_constraint(None, 'earnings', type_='foreignkey')
    op.drop_column('earnings', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
