"""test

Revision ID: 892833e3a998
Revises: b53f75417156
Create Date: 2024-01-16 20:28:47.752278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892833e3a998'
down_revision = 'b53f75417156'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
