"""Add user_id

Revision ID: b24d2451ddc6
Revises: fba1b4a97ddf
Create Date: 2024-01-04 22:50:40.174832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24d2451ddc6'
down_revision = 'fba1b4a97ddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'user_id')
    # ### end Alembic commands ###
